# config.yaml
defaults:
  - _self_
  - task: molecular_nis
  - sampler_net: rbm
  - ansatz: vit_sa

fullsum: true

hydra:
  run:
    # Structure logs by Molecule ID, Network Type, and Date
    dir: outputs/fs/${system.cid}/${ansatz.name}/${sampler_net.name}/${training.n_s}/${now:%Y-%m-%d_%H-%M}
outdir: outputs/fs/${system.cid}/${ansatz.name}/${sampler_net.name}/${training.n_s}/${now:%Y-%m-%d_%H-%M}

system:
  cid: 947 # N2
  basis: "STO-3G"
  # cache_dir: "/leonardo_work/EUHPC_A05_006/Antoine/NeurIS/qchem_utils/pubchem_cache"
  cache_dir: '/Users/antoine.misery/Documents/These/projects/importance_sampling/qchem_utils/pubchem_cache'
exact_sampling: false

training:
  n_s: 1024
  seed: 0
  
  pretrain:
    iterations: 200
    lr: 0.05
    diag_shift: 1e-4
    use_ngd_sampler: false
    use_ngd_wf: false
    diag_shift_p: 1e-2 # Specific shift for Backflow pre-training
  
  vmc:
    iterations: 3000
    lr_start: 5e-3
    lr_end: 1e-4
    diag_shift: 1e-4
  
  nis:
    iterations: 1
    update_fn: 'snr_mat'
    lr_start: 1e-2
    lr_end: 7e-3
    diag_shift: 1e-5