# config.yaml
defaults:
  - _self_
  - task: molecular_nis
  - sampler_net: fermionar
  - ansatz: mlp

hydra:
  run:
    # Structure logs by Molecule ID, Network Type, and Date
    dir: outputs/${system.cid}/${ansatz.name}/${sampler_net.name}/${now:%Y-%m-%d_%H-%M}
outdir: outputs/${system.cid}/${ansatz.name}/${sampler_net.name}/${now:%Y-%m-%d_%H-%M}

system:
  cid: 166630 # Li2O
  basis: "STO-3G"
  cache_dir: "/leonardo_work/EUHPC_A05_006/NeurIS/qchem_utils/pubchem_cache"

exact_sampling: false

training:
  n_s: 1024
  seed: 0
  
  pretrain:
    iterations: 100
    lr: 0.05
    diag_shift: 1e-4
    use_ngd_sampler: false
    use_ngd_wf: false
    diag_shift_p: 1e-2 # Specific shift for Backflow pre-training
  
  vmc:
    iterations: 3000
    lr_start: 5e-2
    lr_end: 1e-2
    diag_shift: 1e-4
  
  nis:
    iterations: 1
    update_fn: 'snr_mat'
    lr_start: 1e-4
    lr_end: 1e-4
    diag_shift: 1e-1